### PR TITLE
Change default space config direction

### PR DESCRIPTION
**Pull request by joshuanianji**
## Description

This changes the default space config direction to horizontal. 

## Action Items

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] This PR is as small as it can be, and only implements on thing (not many)
- [x] I have manually tested my feature
- I have written a "good" amount of tests (including visual and unit tests) (not necessary)

### CODE REVIEW

**Comment by supermacro** [comment]
Great stuff @joshuanianji! 

I haven't taken a look at the code yet, but I noticed that the `Button` examples are all wonky now!

Screen Shot 2020-10-14 at 12 34 40 PM

Please update the direction on these examples to prevent this breaking change.

Also, run `./scripts/format-elm-files.sh` to format your files.

**Comment by joshuanianji** [comment]
Oh I didn't think about changing the other examples! My new commits should all work now.

**Comment by supermacro** [comment]
I just noticed that the docs are incorrect now. 

Do a `grep` for `Note that by default, a Space value is set to be vertically layed out with a "small" within `src/Ant/Space.elm` space between elements`. Please update this documentation accordingly.

**Comment by joshuanianji** [comment]
Alright, the docs are fixed now. How does it look?

**Review by supermacro — APPROVED** [review]

**Comment by supermacro** [comment]
Once #53 is merged I'll push a new release to https://package.elm-lang.org/

**Comment by supermacro** [comment]
`v4.2.3` is live :)

https://github.com/supermacro/elm-antd/releases/tag/4.2.3

**Pull request merged**
