### PR TITLE
first iteration on Drawer component, including showcas and some…

### PR DESCRIPTION
**Pull request by effe-megna**
… primitives to create it.

This pull request include a first iteration around the Drawer component. I've had prepared the showcase and a basic way to create the Drawer. Anyway i need to find a way to update the model for handle the display/hide functionality, for now the Drawer remain open.

As you can see right now the Drawer miss some basic functionality like control the width/height, or trigger the event to close it. I want to know if i'm on the right road or I'm totally wrong with this approach.

Also it's my first pull-request, so be kind 😄 

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] This PR is as small as it can be, and only implements on thing (not many)
- [x] I have manually tested my feature
- [ ] I have written a "good" amount of tests (including visual and unit tests)

### CODE REVIEW

**Comment by Orasund** [comment]
I've only looked at the `src\Ant\Drawer.elm` file.

Looks good, no mayor error as far as im aware of. One small thing I dislike is that you set the default name to "Drawer". As a non english speaker this mean i would alway need to change the name whenever i use the widget. Best to change it to `Title ""` or even better: make it optional.

Other than that: Great.

**Comment by supermacro** [comment]
Note that you'll want to remove the Drawer from the list of unimplemented components:

https://github.com/supermacro/elm-antd/blob/master/showcase/src/elm/Router.elm#L123

**Comment by effe-megna** [comment]
Thx for the feedback,

`One small thing I dislike is that you set the default name to "Drawer".` yes i forgot the hardcoded string inside , fixed using an empty string.

`Note that you'll want to remove the Drawer from the list of unimplemented components:` I already removed the Drawer from that list.

Regarding the closing of the Drawer: before explore the best way to do that I need to understand how i can dispatch Msg from a `DemoBox` and update the relative model, any suggestion?

After that i will explore the documentation of ant about Mask

**Comment by supermacro** [comment]
@effe-megna 

> before explore the best way to do that I need to understand how i can dispatch Msg from a DemoBox and update the relative model, any suggestion?

Check out this change I made to your `Drawer` branch.

[src.zip](https://github.com/supermacro/elm-antd/files/4891883/src.zip)

You can unzip and replace `showcase/src` with this file to view a diff of the changes I made. Feel free to either push or make additional modifications. 

**Demo**: https://www.loom.com/share/29280d41a3f54839a1d1c185adf27b72

**Comment by effe-megna** [comment]
@supermacro 

Perfect, now I can interact with the Model, thank you. I will continue to work on it 👍

**Comment by supermacro** [comment]
FYI:

- When creating a new component, make sure to add it to the `exposed-modules` array inside `elm.json`
- Ensure any exposed functions or types are documented, otherwise `elm publish` does not let me create a new version. Refer to the following commits:
  - https://github.com/supermacro/elm-antd/commit/3adf53b5dde940e3624e04e2e8bb7861b32e3c01
  - https://github.com/supermacro/elm-antd/commit/419ecfcd41c3e403f1fa0f2bbe7d78046a1a25a6

I think you can run `elm publish` on your computer to do a test run and make sure that your code is in a "publishable" state.

**Comment by effe-megna** [comment]
Oh, TIL

got it 👍

**Comment by supermacro** [comment]
I noticed that the there's a parse error on `Router.elm`. 

Error:

https://app.circleci.com/pipelines/github/supermacro/elm-antd/71/workflows/060ade37-84fc-418e-9d40-a9e7d1e46804/jobs/312/steps

Seems to have come up when I was resolving a merge conflict. 

Besides this small error (and the above comments I made), is there any other outstanding work needed to get `Drawer` into `master`?

**Comment by effe-megna** [comment]
Hey,

About the Drawer, I'm stuck with two things:
 - Mask concept, suggested by @Orasund 
 - Animation

I will push some works tomorrow, mainly about UI, but I probably need some help about Mask, useful for implement this [example](https://ant.design/components/drawer/#components-drawer-demo-multi-level-drawer)

**Comment by supermacro** [comment]
Hey @effe-megna, wanted to check in and see how you're doing. Do you plan to continue working on this PR or should someone take it over?

**Comment by effe-megna** [comment]
Hey folks,

sorry for this idle time, I'm overwhelmed these days, anyway I plan to continue my pull-requests this week

**Comment by supermacro** [comment]
Hey @effe-megna,

I am going to close this PR for now. There are already quite a few conflicts and I plan on merging code that will add even more conflicts.

Feel free to re-open this PR (or ping me to re-open) or open a new one any time in the future, though!

Gio

**Pull request closed without merging**
